### ISSUE TITLE
[M0 - Dev] Aclaración sobre la estructura de datos completa

### ISSUE THREAD

**Issue by mariavallejo20** [PacoCP5/proyecto-PCP#11]
Hola de nuevo @PacoCP5!! He creado este issue para tener una visión general de la estructura de datos de la que hemos hablado estos días en relación a la HU1[#3], para ver si lo tenemos todo, aclarando cualquier duda y ponerme con ello. La estructura de datos que entiendo en función a lo hablado en los issues #8 y #9, es la que te dejo abajo.

Además he añadido lo que creo que es necesario para implementar la lógica de negocio de la HU1, sin embargo, me gustaría aclararlo bien para tenerlo todo claro a la hora de la implementación.

Sobre la clase horario te he dejado un comentario en el issue https://github.com/PacoCP5/proyecto-PCP/issues/8, para ver que te parece utilizar hash o si tienes una idea mejor.

# Estructura de datos 
## Clase Turno
* Tipo de turno (enum: mañana, tarde, noche)
* Box asignado (enum: A, B, C, D)

## Clase Trabajador 
* ID del trabajador
* Nombre

## Clase turnoTrabajador
* Fecha del turno
* Turno
* Lista de trabajadores

## Clase horario
* Semana 
* Lista de objetos TurnoTrabajador

Coméntame que piensas. 😊

**Comment by mariavallejo20** [comment]
Hola de nuevo @PacoCP5!! He creado este issue para tener una visión general de la estructura de datos de la que hemos hablado estos días, para ver si lo tenemos todo y ponerme con ello. ¿Crees que está bien así?

Sobre la clase horario te he dejado un comentario en el issue #8, para ver que te parece utilizar hash o si tienes una idea mejor.

Coméntame que piensas. 😊

**Comment by PacoCP5** [comment]
Hola!

Me parece genial, para tenerlo claro, en el hash, la clave sería el turno y el valor una lista de trabajadores no?

También como comentario, los valores del tipo de turno son fijos, así que lo suyo es que sea un Enum. Ruby no tiene este tipo de datos por defecto, pero se puede implementar usando un módulo específico como Enum. Si tienes alguna duda respecto a esto me dices.

Ánimo que ya queda poco :)

**Comment by mariavallejo20** [comment]
Hola de nuevo @PacoCP5!!! He estado dándole una vuelta a mi propuesta y aunque no me parece que esté mal he pensado algo que creo que se adecuará mejor a lo que buscamos:
- Añadir una clase  "TurnoTrabajador" que relacione un turno con una lista de trabajadores, que será aquí donde posteriormente se cree el método necesario para las asignaciones.
- Almacenar en la clase "Horario" una lista de objetos "TurnoTrabajador", que este ya si sería un horario completo, de una semana, por ejemplo.

Con lo que te propongo la estructura sería la siguiente:
 **Clase Turno**
* Fecha del Turno
* Tipo de Turno (mañana, tarde, noche)
* Box

**Clase Trabajador**
* ID del trabajador
* Nombre

**Clase TurnoTrabajador**
* Turno
* Lista de Trabajadores

**Clase Horario**
* Lista de TurnoTrabajador


Dime que te parece, si crees que es mejor idea que la anterior y si piensas que sobraría o faltaría algún atributo en alguna de las clases.🤔😅

**Comment by mariavallejo20** [comment]
¿Crees que sería necesario añadir algún tipo de identificador en la clase Turno para poder identificar un turno al igual que hemos hecho con los trabajadores? 🤨

**Comment by PacoCP5** [comment]
Hola, me parece una mejor idea lo que propones, aunque respecto a los atributos hay algunas cosas que haría diferente:

- En primer lugar, pondría el atributo fecha de la clase Turno en la clase TurnoTrabajador, ya que así este representaría un turno de un día asignado a varios trabajadores.
- Por otro lado, respecto a la clase Horario, también le añadiría un atributo que indicase la semana que le corresponde (en principio un string o tal vez un objeto de alguna clase Date o similar)

Respecto a tu otra pregunta, al final un turno está determinado por el tipo de turno y el box asignado, así que no creo que sea necesario un ID para identificarlo.

También comentarte que he decidido que haya un número fijo de boxes (A,B,C y D por ejemplo), para simplificar un poco la programación, así que también sería conveniente que el tipo de datos del atributo box de la clase Turno fuese un enum.

Me comentas a ver qué te parece o si tienes alguna consulta más :smile:

**Comment by mariavallejo20** [comment]
De acuerdo, me parece buena idea, ya que así tendríamos:
* Turno y Trabajador como objetos valores ya que son inmutables
* TurnoTrabajador y Horario como entidades ya que estás son las que cambiarán
 
He modificado y añadido los atributos en la estructura de datos inicial de arriba para tener lo que hemos hablado. Échale un vistazo y me dices si está todo correcto. 🤗

**Comment by PacoCP5** [comment]
Lo veo bien, ahora toca implementarlo! :+1:
