### ISSUE TITLE
[M0 - Dev] Duda sobre la base de datos a utilizar

### ISSUE THREAD

**Issue by mariavallejo20** [PacoCP5/proyecto-PCP#12]
Hola @PacoCP5. ¿Has buscado o tienes alguna base de datos con la que podamos trabajar? Si es así dime cual es para poder ver los valores que toman las distintas variables y adecuarlo a la estructura de datos que hemos estado hablando en el issue #11.

Gracias de nuevo, un saludo. 😊

Asignado a la HU1[#3 ]

**Comment by PacoCP5** [comment]
Hola!

Pues desafortunadamente, no he encontrado información real acerca de este problema, ya que por temas de protección de datos y eso no es fácil encontrar este tipo de información.

Lo consultaré en la próxima clase con el profesor, aunque ya hablamos de este tema para ver qué hago, pero yo creo que al final acabaré usando información ficticia.

**Comment by mariavallejo20** [comment]
De acuerdo, cuando lo consultes con el profesor me cuentas. 😇
