### ISSUE TITLE
[M0 - Dev] Aclaración sobre los distintos tipos de boxes

### ISSUE THREAD

**Issue by mariavallejo20** [PacoCP5/proyecto-PCP#13]
Hola @PacoCP5 como me comentas en la HU1[#3] tenemos diferentes turnos y como hemos hablado en el issue #8, en cada turno tenemos que asignarle un box, teniendo la estructura final del issue #11. Atendiendo a la corrección del profesor, creo que debemos concretar que tipos de boxes diferentes podemos tener.

¿Qué piensas tú sobre esto? 🤔

**Comment by mariavallejo20** [comment]
Acuérdate de asignar este issue al M0. 🤩

**Comment by PacoCP5** [comment]
Hola! Pues yo creo que lo mejor es seguir dejando un enum pero en vez de A,B.. pues que hayan dos tipos de box según el tipo de trabajo, normal y refuerzo.

**Comment by mariavallejo20** [comment]
De acuerdo, me parece una buena idea y más clara que nuestra idea principal. 🙌

**Comment by JJ** [comment]
> Hola! Pues yo creo que lo mejor es seguir dejando un enum pero en vez de A,B.. pues que hayan dos tipos de box según el tipo de trabajo, normal y refuerzo.

La persona que programa es quien tiene que decidir qué pone y qué no. Tú debes limitarte a decir qué vas a usar en la lógica de negocio, si no queda suficientemente claro en el HU.
