### ISSUE TITLE
Elección del gestor de tareas

### ISSUE THREAD

**Issue by PacoCP5** [PacoCP5/proyecto-PCP#15]
Es necesario un gestor de tareas que lleve a cabo de forma automática las tareas de comprobar la sintaxis de las entidades, la ejecución de test y la instalación de dependencias, que sea rápido y tenga un mantenimiento frecuente (frescura)

**Comment by JJ** [comment]
Todos los issues deben representar un problema. En este caso también. Tendrás que decir qué es lo que tiene que hacer el gestor de tareas, por ejemplo.

**Comment by PacoCP5** [comment]
Creo que está claro. Tiene que "comprobar la sintaxis de las entidades, la ejecucción de test y la instalación de dependencias"

**Comment by JJ** [comment]
> Creo que está claro. Tiene que "comprobar la sintaxis de las entidades, la ejecucción de test y la instalación de dependencias"

Eso lo hace cualquier gestor de tareas. Si no lo hace, es que no es un gestor de tareas.
