### ISSUE TITLE
Archivos necesarios en la imagen relativos a las dependencias

### ISSUE THREAD

**Issue by PacoCP5** [PacoCP5/proyecto-PCP#32]
Necesito saber cuáles son los archivos necesarios a la hora de construir la imagen y cuáles necesita la imagen para satisfacer las dependencias de la aplicación

**Comment by PacoCP5** [comment]
Si no copio el Gemfile y el Gemfile.lock cuando construyo la imagen no puedo hacer `bundle install` para instalar las dependencias, si esos archivos sobran no sé cómo hacerlo. Por favor, ayúdame a ver cómo lo hago @JJ

**Comment by JJ** [comment]
Una vez más, nadie te ha dicho que no los copies. Lee mi comentario y lo que digo sobre la diferencia que hay entre archivos necesarios para construir la imagen y archivos que deben quedarse en la imagen.
