### ISSUE TITLE
[M0 - Dev] Aclaración de la lógica de negocio.

### ISSUE THREAD

**Issue by mariavallejo20** [PacoCP5/proyecto-PCP#7]
Hola de nuevo @PacoCP5!! :stuck_out_tongue_winking_eye:
Me gustaría que me explicaras un poco la lógica de negocio, para tenerla totalmente clara, ya que no me queda clara con la HU1[#3].

**Comment by PacoCP5** [comment]
Hola! Claro que sí.

La lógica de negocio principal es la asignación del horario de trabajo los distintos enfermeros a los distintos pacientes. El cliente principal sería el hospital (principalmente la enfermera veterana o el encargado de realizar la asignación del horario, que por lo que sé hasta ahora en la mayoría de sitios se hace a mano y en papel).

La asignación de horarios se realiza a dos niveles. Por un lado, tenemos los turnos en un día (mañana, tarde y noche) y por otro lado la asignación a los distintos boxes de pacientes (esto es un número variable que dependerá del hospital y suelen estar etiquetados con letras A, B, C... etc).

Posteriormente, a esta lógica de negocio me gustaría añadir que los trabajadores puedan expresar su preferencia en los turnos y que se tenga en cuenta a la hora de realizar la asignación dentro de lo posible y que sea lo más justo posible.

A ver si te ha quedado claro, cualquier duda me preguntas :)

**Comment by mariavallejo20** [comment]
Cuando dices que la asignación se realiza a dos niveles, ¿te refieres a que, a la hora de asignar un turno, hay que tener en cuenta el turno del día que se asignará y el box de pacientes en el que deberá estar el trabajador?

¿Tienes alguna idea pensada para el tema de que los diferentes trabajadores expresen su preferencia con los turnos?

Gracias :kissing_closed_eyes:

**Comment by PacoCP5** [comment]
Sí, exacto, en cada turno de mañana, tarde y noche hay una asignación de un número determinado de enfermeros a cada box de pacientes.

La verdad que tengo todavía que pensar el algoritmo para tener en cuenta la preferencia y no sé muy bien como representarla, tal vez lo suyo sería fijar los horarios de los que han expresado su preferencia y organizar el resto según esto. Aunque el problema de esto sería que los trabajadores siempre elegirán el box de pacientes que les suponga menos trabajo, así que debería limitar la elección de turnos de alguna forma.

En cualquier caso eso no influye en la representación del modelo de momento, y si luego se me ocurre una forma que influya haré los cambios yo en un milestone posterior.

Cualquier aclaración me dices :smiley_cat:

**Comment by mariavallejo20** [comment]
Perfecto @PacoCP5, ahora entiendo perfectamente la lógica de negocio de tu servicio. Gracias. :punch:
