### ISSUE TITLE
[M0 - Dev] Aclaración sobre los turnos.

### ISSUE THREAD

**Issue by mariavallejo20** [PacoCP5/proyecto-PCP#8]
Hola @PacoCP5!! Quiero comentarte algunas dudas que tengo sobre los turnos. Según he entendido en función a la HU1[#3], creo que estos serían los atributos de un turno:
* Fecha del turno
* Horario del turno (mañana, tarde o noche). Aunque no se si sería necesario también añadir la hora de inicio y de fin de cada turno. ¿Qué piensas tú?
* Box asignado 
* Lista de los trabajadores que formarán parte del turno.

¿Crees que sobra o falta algún atributo?
Por otro lado, no estoy segura si el último atributo debe formar parte de esta clase o mejor de la clases trabajadores, ya que es cada trabajador el tiene un conjunto de turnos. échale un ojo y me dices que piensas tú. :sunglasses:

**Comment by PacoCP5** [comment]
Hola!

Creo que los atributos están bien. Respecto al horario del turno creo que las horas de inicio y fin son fijas, así que no es necesario añadirlas.

Por otro lado, respecto a la lista de los trabajadores, estos van a ser representados a través de un Id fijo, así que la lista de los trabajadores sería una lista de los Ids.

Cualquier aclaración más me dices y disculpa por tardar en contestar :sweat_smile:

**Comment by mariavallejo20** [comment]
De acuerdo, me pongo con ello!

**Comment by PacoCP5** [comment]
Hmm, vale! Me parece una mejor idea. Podemos llamar a esta clase Horario si te parece bien y la estructura de datos podría ser algo parecido a un array de pares entre objetos de las clases Trabajador y Turno (habría que ver que no haya turnos repetidos), aunque no sé si tenías otra cosa en mente.

Respecto a lo que comentas de almacenar la lista de trabajadores de cada turno creo que sería útil a la hora de consultarlos, pero no sé si es buena idea almacenarlo en la clase Turno, ya que habría que añadir esta lista después de que se lleve a cabo la lógica de negocio y los Turnos se deben crear antes para poder asignarlos a un trabajador en la clase Horario. 

Para la último, tal vez podríamos añadir alguna estructura en la clase Horario, aunque así de primeras no se me ocurre nada, si tienes alguna idea o propuesta no dudes en decírmela :D

**Comment by mariavallejo20** [comment]
Mi idea para la clase Horario sería almacenar los pares de valores Turno-Trabajador en una tabla hash, que es lo que se suele utilizar para relacionar objetos entre sí. ¿Qué te parece?

**Comment by PacoCP5** [comment]
Me parece bien!

**Comment by JJ** [comment]
No está asignado a una hU.
