### ISSUE TITLE
[M0 - Dev] Aclaración sobre los trabajadores.

### ISSUE THREAD

**Issue by mariavallejo20** [PacoCP5/proyecto-PCP#9]
Hola @PacoCP5!! He creado este issue para saber que piensas sobre los trabajadores que forman parte del servicio. Me gustaría preguntarte algunas cosas para que me aclares que piensas tú, en función a lo que he podido ver en la HU1[#3]:
* ¿Cada trabajador tendría una ID, con la que los identificaríamos?
* De cada trabajador, creo que tendríamos "Nombre y Apellidos", ¿Crees que sería necesario algún dato más?
* ¿Un trabajador tendrá una lista de turnos asignados? Este tema te lo he comentado también en el issue #8

Cuando tengas un rato me cuentas tu opinión!!

**Comment by PacoCP5** [comment]
Hola!

Parte de tu duda te la he contestado en el issue #8. Te la aclaro aquí mejor: lo suyo es que la clase trabajador sea un objeto inmutable, así que no creo que sea necesario almacenar los turnos en cada trabajador, ya que esta información se guardaría en la clase que representa los turnos, porque si no sería un poco información redundante, aunque tal vez para acceder luego a los turnos de cada trabajador sea algo más complicado, pero en principio lo dejamos así.

**Comment by mariavallejo20** [comment]
De acuerdo @PacoCP5!
Por otro lado, me gustaría saber que piensas sobre la identificación de cada trabajador, ¿Lo hacemos con una ID, con el correo electrónico, con el teléfono? ¿De cada trabajador, a parte de "Nombre y Apellidos" crees que sería necesario algún otro dato?🤔

**Comment by PacoCP5** [comment]
Respecto al ID, creo que con un identificador numérico que se autoincremente de alguna forma será suficiente. Respecto a los otros datos, en principio para realizar la asignación no se tiene en cuenta la preferencia, tal vez lo añada luego, pero de momento solamente deja Nombre y Apellidos.

**Comment by mariavallejo20** [comment]
Perfecto @PacoCP5 😁
